### ISSUE TITLE
API documentation warnings

### ISSUE THREAD

**Issue by TimBartholomew** [nawi-hub/proteuslib#143]
When I originally run ``make html`` from a fresh pull of ProteusLib main I receive the following warnings:

```
(proteuslib) PS C:\Users\timvb\idaes\proteuslib\docs> ./make html
Creating file apidoc\proteuslib.rst.
Creating file apidoc\proteuslib.edb.rst.
Creating file apidoc\proteuslib.flowsheets.rst.
Creating file apidoc\proteuslib.flowsheets.RO_with_energy_recovery.rst.
Creating file apidoc\proteuslib.property_models.rst.
Creating file apidoc\proteuslib.unit_models.rst.
Creating file apidoc\modules.rst.
Running Sphinx v4.0.2
loading pickled environment... done
myst v0.15.1: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['dollarmath', 'amsmath', 'deflist', 'html_admonition', 'html_image', 'colon_fence', 'smartquotes', 'replacements', 'linkify', 'substitution', 'tasklist'], dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=True, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['http', 'https', 'mailto', 'ftp'], heading_anchors=2, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 10 source files that are out of date
updating environment: 5 added, 10 changed, 2 removed
reading sources... [100%] technical_reference/index
C:\Users\timvb\idaes\proteuslib\proteuslib\flowsheets\RO_with_energy_recovery\RO_with_energy_recovery.py:docstring of proteuslib.flowsheets.RO_with_energy_recovery.RO_with_energy_recovery.calculate_operating_pressure:10: WARNING: Definition list ends without a blank line; unexpected unindent.
C:\Users\timvb\idaes\proteuslib\proteuslib\unit_models\nanofiltration_0D.py:docstring of proteuslib.unit_models.nanofiltration_0D.NanoFiltrationData.initialize:3: WARNING: Unexpected indentation.
C:\Users\timvb\idaes\proteuslib\proteuslib\unit_models\nanofiltration_0D.py:docstring of proteuslib.unit_models.nanofiltration_0D.NanoFiltrationData.initialize:6: WARNING: Block quote ends without a blank line; unexpected unindent.
C:\Users\timvb\idaes\proteuslib\proteuslib\unit_models\pressure_exchanger.py:docstring of proteuslib.unit_models.pressure_exchanger.PressureExchangerData.initialize:3: WARNING: Unexpected indentation.
C:\Users\timvb\idaes\proteuslib\proteuslib\unit_models\pressure_exchanger.py:docstring of proteuslib.unit_models.pressure_exchanger.PressureExchangerData.initialize:4: WARNING: Block quote ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
pickling environment... done
checking consistency... C:\Users\timvb\idaes\proteuslib\docs\apidoc\modules.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] technical_reference/index
generating indices... genindex py-modindex done
highlighting module code... [100%] proteuslib.unit_models.reverse_osmosis_0D   k.financialsergy_recovery
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 6 warnings.
```

But when I run ``make html`` again, I get no warnings:

```
(proteuslib) PS C:\Users\timvb\idaes\proteuslib\docs> ./make html
Creating file apidoc\proteuslib.rst.
Creating file apidoc\proteuslib.edb.rst.
Creating file apidoc\proteuslib.flowsheets.rst.
Creating file apidoc\proteuslib.flowsheets.RO_with_energy_recovery.rst.
Creating file apidoc\proteuslib.property_models.rst.
Creating file apidoc\proteuslib.unit_models.rst.
Creating file apidoc\modules.rst.
Running Sphinx v4.0.2
loading pickled environment... done
myst v0.15.1: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['dollarmath', 'amsmath', 'deflist', 'html_admonition', 'html_image', 'colon_fence', 'smartquotes', 'replacements', 'linkify', 'substitution', 'tasklist'], dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=True, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['http', 'https', 'mailto', 'ftp'], heading_anchors=2, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
no targets are out of date.
build succeeded.
```
I get the warnings again if I delete the apidoc folder, so these warnings are tied to *whether the apidoc folder exists initially or not*. I understand why warnings about docstrings would not be repeated if the apidoc doesn't need to be generated, but I don't know why the warning that the apidoc\modules.rst document isn't included in any toctree goes away because I believe the file still isn't in a toctree outside of the apidoc folder.

Regardless we should address these warnings. I don't know if the best route is to include the apidoc in the code base, or if we should make that an untracked file. I'm under the impression that the apidoc is rewritten each time `make html` is called, so I'm leaning towards making it an untracked file.

**Comment by adam-a-a** [comment]
Following what I observed in the IDAES repo, I added docs/apidoc to the .gitignore file (in one of the latest commits to #142). 

Similar to @TimBartholomew , I also noticed that running `make html` more than once in a row will lead to warnings no longer being shown and receiving a "build succeeded" message on my local machine. I think this is because we don't have -E option enabled for sphinx-build (i.e., in the make.bat file), which apparently does the following: 

> Don’t use a saved environment (the structure caching all cross-references), but rebuild it completely. The default is to only read and parse source files that are new or have changed since the last run.

On the other hand, this won't eliminate all the warnings you get due to the existence of the apidoc folder when running `make html`. I found that modifying sphinx-api options in the make.bat file and deleting the apidoc folder (if it was generated previously) can avoid this issue of seeing warnings related to files generated in the apidoc folder. 

We can modify the following line: 
`%SPHINXAPIDOC%  -f -M -H ProteusLib -d 3 -o apidoc ../proteuslib "../*tests*"
`
by removing `-o apidoc ../proteuslib`, which is saying to output files (-o) to a directory (named "apidoc") and generate those files based on the content in the proteuslib directory (../proteuslib). 

In fact, we could go a step further and delete the whole line `%SPHINXAPIDOC%  -f -M -H ProteusLib -d 3 -o apidoc ../proteuslib "../*tests*"` to avoid the aforementioned warnings, which leads us to the next to question: why do we need this line to be included in the make.bat file in the first place? 

I am guessing this will come in handy later on when the project matures and our documentation needs increase, but maybe someone more knowledgeable on the matter can fill us in. @dangunter @ksbeattie @lbianchi-lbl @bknueven

**Comment by adam-a-a** [comment]
The alternative we want to go with is adding a `:noindex:` directive to all of the "hand-written" files that conflict with the api-docs.

**Comment by adam-a-a** [comment]
@dangunter @ksbeattie @lbianchi-lbl  Actually, another warning that I wasn't sure how to resolve (which is why I opted for preventing the generation of the apidoc folder previously) was `proteuslib\docs\apidoc\modules.rst: WARNING: document isn't included in any toctree`

The `modules.rst` file that is generated within the apidoc folder should be included in a toctree somewhere.... but where? I tried looking to IDAES as an example, to no avail.

**Comment by bknueven** [comment]
I think it should be at the highest level -- so that it appears on the left side index just above the license agreement and copyright.

**Comment by adam-a-a** [comment]
Ah, yes - I tried that before and listed it as "Module Index" but wasn't crazy about also having the Module Index listed under "Indices and tables" on the main page. I guess it's not that big of a deal.

**Comment by adam-a-a** [comment]
Ultimately, we decided to just comment out the %SPHINXAPIDOC% build line until a better solution comes along.
