### ISSUE TITLE
Update specific enthalpy in property packages

### ISSUE THREAD

**Issue by TimBartholomew** [nawi-hub/proteuslib#41]
Currently the specific enthalpy calculations in the property packages only include internal energy and do not include the pressure-volume term.

**Comment by TimBartholomew** [comment]
The pressure-volume term is tricky for an incompressible fluid, the best approach is to add is_isothermal options to unit models and remove the energy balance. More thought needs to go into making the liquid property packages thermodynamically consistent.

**Comment by andrewlee94** [comment]
To record a conversion @TimBartholomew and I had, it is more a question of recognizing the effects of assumptions made. Assuming an incompressible fluid means that you either have to accept that compression work goes entirely to heating the fluid, or that energy conservation cannot be maintained. Similarly, assuming an ideal gas means that it costs no energy to compress the gas.

In terms of how this needs to be implemented in models, this needs more thought (in part to help users not make mistakes). One option would be to have property packages which assume incompressible fluids set `default_energy_balance_type` to a new `isothermal` value. This would mean that the control volumes would by default add a temperature equality constraint instead of an energy balance. Users could then overload this if desired, but they would need to be aware of the effects.
