### ISSUE TITLE
Dealing with very small quantities and bounds

### ISSUE THREAD

**Issue by andrewlee94** [nawi-hub/proteuslib#47]
By nature, electrolyte solutions involve a lot of very small concentrations which cause scaling and numerical issues. One issue that has been brought up is the effect of IPOPT's bound push function, which perturbs values close to bounds. For trace species, where concentrations are very small and there is a lower bound of 0, this results in challenges when using IPOPT.

We need to to think about the best approach to dealing with this.

**Comment by aladshaw3** [comment]
Here are some scaling methods that I have found work very well with aqueous species at very low concentration levels.

(1) When using 'log_power_law' functions, make sure the 'eps' is at least 2-orders magnitude less than the value of 'k_eq'
```
for rid in model.fs.thermo_params.inherent_reaction_idx:
     scale = value(model.fs.unit.control_volume.properties_out[0.0].k_eq[rid].expr)
     if scale < 1e-16:
          model.fs.thermo_params.component("reaction_"+rid).eps.value = scale*1e-2
     else:
          model.fs.thermo_params.component("reaction_"+rid).eps.value = 1e-16*1e-2
```

(2) Scale the 'extent' of reaction by 10 divided by the value of 'k_eq' and scale the equilibrium constraint by 0.1. NOTE: The reason the constraint is scaled in this manner is because we use the 'log_power_law' form. In this form, the constraint is inherently already 'scaled' well by the way the constraint is redefined in terms of the log of the original expression. 
```
for i in model.fs.unit.control_volume.inherent_reaction_extent_index:
      scale = value(model.fs.unit.control_volume.properties_out[0.0].k_eq[i[1]].expr)
      iscale.set_scaling_factor(model.fs.unit.control_volume.inherent_reaction_extent[0.0,i[1]], 10/scale)
      iscale.constraint_scaling_transform(model.fs.unit.control_volume.properties_out[0.0].
                    inherent_equilibrium_constraint[i[1]], 0.1)
```

(3) Scale the variables and mass balance constraints based on the inlet values given and/or some minimum molefraction (which I found 1e-10 to be adequate).
```
min = 1e-10
for i in model.fs.unit.control_volume.properties_out[0.0].mole_frac_phase_comp:
      if model.fs.unit.inlet.mole_frac_comp[0, i[1]].value > min:
          scale = model.fs.unit.inlet.mole_frac_comp[0, i[1]].value
      else:
          scale = min
      iscale.set_scaling_factor(model.fs.unit.control_volume.properties_out[0.0].mole_frac_comp[i[1]], 10/scale)
      iscale.set_scaling_factor(model.fs.unit.control_volume.properties_out[0.0].mole_frac_phase_comp[i], 10/scale)
      iscale.set_scaling_factor(model.fs.unit.control_volume.properties_out[0.0].flow_mol_phase_comp[i], 10/scale)
      iscale.constraint_scaling_transform(
                model.fs.unit.control_volume.properties_out[0.0].component_flow_balances[i[1]], 10/scale)
      iscale.constraint_scaling_transform(model.fs.unit.control_volume.material_balances[0.0,i[1]], 10/scale)
```

You can see this in action in the `test_phosphorus_removal.py` unit test. These are the best options I have found so far. Additional testing will be needed for how to scale with other phases (gases and liquids). 

Also note: The written code samples are explicitly for 'inherent' reactions. The same logic works for 'equilibrium' reactions, but the methods you call will be different because the objects are located in different parts of the model.

**Comment by aladshaw3** [comment]
I don't think we should be leaving this up as an issue. While it is still a consistent problem, it is not something that will be resolved by a PR. However, I have done the documentation that discusses the best scaling methods so far  (#198).
